# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-14 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0004_auto_20190414_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_sittings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=120, verbose_name='رقم الدعوى')),
                ('sitting_date', models.DateTimeField(blank=True, max_length=120, null=True, verbose_name='تاريخ الجلسه')),
                ('sitting_decision', models.TextField(blank=True, max_length=120, null=True, verbose_name='   قرار الجلسه')),
                ('ip', models.CharField(blank=True, max_length=120, null=True)),
                ('attend_lawyer', models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.case_lawyer', verbose_name='اسم المحامى  الحاضر')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='law_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=120, verbose_name='رقم الدعوى')),
                ('case_year', models.CharField(blank=True, max_length=120, null=True, verbose_name='سنة الدعوى')),
                ('case_subject', models.CharField(blank=True, max_length=120, null=True, verbose_name='موضوع الدعوى')),
                ('case_subject_detail', models.TextField(max_length=120, verbose_name='موضوع الدعوى تفصيلا')),
                ('last_sitting', models.CharField(max_length=120, verbose_name='اخر جلسه')),
                ('expected_financial_affairs', models.CharField(max_length=120, verbose_name='الاعباء الماليه المتوقعه')),
                ('notes', models.TextField(blank=True, max_length=120, null=True, verbose_name='ملاحظات')),
                ('date_of_establsihment', models.CharField(max_length=120, verbose_name='تاريخ الورود')),
                ('ip', models.CharField(blank=True, max_length=120, null=True)),
                ('adversary', models.ForeignKey(max_length=2048, on_delete=django.db.models.deletion.CASCADE, to='app1.oponent', verbose_name='الخصم ')),
                ('adversay_represent', models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.oponentrep', verbose_name='صفة الخصم ')),
                ('case_category', models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.case_category', verbose_name='تصنيف الدعوى')),
                ('case_classification', models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.case_classification', verbose_name='نوع الدعوى')),
                ('case_court', models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.case_court_name', verbose_name='المحكمه  ')),
                ('case_current_status', models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.case_current_status', verbose_name='حالة الدعوى')),
                ('case_depart', models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.casedep', verbose_name='  الدائره')),
                ('case_depart_type', models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.case_depart_type', verbose_name=' نوع الدائره  ')),
                ('comapny_represent', models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.comprep', verbose_name='صفة الشركه ')),
                ('current_lawyer', models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.case_lawyer', verbose_name='المحامى المباشر')),
                ('degree_of_litigation', models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.litigationdeg', verbose_name='درجة التقاضى')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weighted_percent_of_gain', models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='app1.gainwtpercent', verbose_name='ترجيح ونسبة الكسب')),
            ],
        ),
    ]
